# Generated by Django 5.1.5 on 2025-01-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='event',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
    ]
