# Generated by Django 5.1.5 on 2025-01-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_remove_itinerary_user_itinerary_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='unnamed', max_length=100),
        ),
    ]
