# Generated by Django 5.1.5 on 2025-01-16 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itineraries.event'),
        ),
    ]
