# Generated by Django 5.1.5 on 2025-01-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0010_alter_itinerary_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='time',
            new_name='from_time',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
