# Generated by Django 5.1.5 on 2025-01-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0011_rename_date_itinerary_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
