# Generated by Django 5.1.5 on 2025-01-16 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0012_place_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
