# Generated by Django 5.1.5 on 2025-01-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0014_alter_place_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.TextField(),
        ),
    ]
