# Generated by Django 5.1.5 on 2025-01-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0008_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5fd78f', max_length=6),
        ),
    ]
