# Generated by Django 5.1.5 on 2025-01-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0007_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c97f7c', max_length=6),
        ),
    ]
