# Generated by Django 4.2.8 on 2025-01-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0009_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='285cc8', max_length=6),
        ),
    ]
